# Github Username
githubUsername = "shanepaton"

# Gitlab ID
gitlabId = "10239709"

# Insert Gitlab Personal Access Token here
gitlabToken = "glpat---JEyXTMFqTZCPgM3Mzs"

# (github / gitlab)
defaultSite = "gitlab"